services:
  pg:
    image: postgis/postgis:17-3.5
    container_name: geolocations-postgres
    environment:
      POSTGRES_USER: ${YOUR DB USERNAME}
      POSTGRES_PASSWORD: ${YOUR DB PASSWORD}
      POSTGRES_DB: ${YOUR DB NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d {YOUR DB NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  web:
    build: .
    ports:
    - "8000:80"
    restart: always
    depends_on:
      - pg

volumes:
  pg_data:
